### ISSUE TITLE
앱 실행후 아이콘 클릭시 나타나는 에러입니다.

### ISSUE THREAD

**Issue by SEUNGHWANYOUN** [naver/navergame-sdk-unity#1]
유니티 버전은 : 2020.3.20f1 사용하였으며,
SDK 버전은 : 1.1.4  사용하였습니다.
Failed resolution of: Lcom/navercorp/nng/android/glideadapter/GlideAdapter

![image](https://user-images.githubusercontent.com/29048275/146475398-6e18478a-c0ae-4702-bcc9-1c0822b47783.png)

**Comment by nerycat32** [comment]
수정되었습니다. 제보 감사합니다.
https://github.com/naver/navergame-sdk-unity/releases/tag/1.1.4_android
